# Generated by Django 5.0.6 on 2024-05-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('exp', models.DecimalField(decimal_places=1, max_digits=2)),
                ('color_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('des', models.CharField(max_length=1024)),
                ('link', models.URLField()),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('skills', models.ManyToManyField(related_name='projects', to='base.skill')),
            ],
        ),
    ]
