# Generated by Django 5.0.6 on 2024-05-09 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_skilltopic_skill_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='color_code',
        ),
    ]
